In [24]:
import pandas as pd
import numpy as np
import sympy as sy
from numpy.random import randn

In [25]:
array_1 = np.array([1,2,3])

In [26]:
array_1

array([1, 2, 3])

In [27]:
type(array_1)

numpy.ndarray

In [28]:
array_2 = np.array([-1,4,2])

In [29]:
print(array_2)

[-1  4  2]


In [30]:
len(array_1)

3

In [31]:
len(array_2)

3

In [32]:
#We want to perform the dot product of these 
#array
for i in range(len(array_1)):
    dot = sum(array_1*array_2)

In [33]:
print(dot)

13


In [34]:
array_1@array_2

13

In [35]:
array_1.dot(array_2)

13

In [36]:
array_3 = array_1**2

In [37]:
array_3

array([1, 4, 9])

In [38]:
print(array_3)

[1 4 9]


In [39]:
L1 = [1,2,3]
L2 = L1*2
L2

[1, 2, 3, 1, 2, 3]

In [40]:
array_4 = np.sqrt(array_1)

In [41]:
print(array_4)

[1.         1.41421356 1.73205081]


In [42]:
array_5 = array_4 +array_1
print(array_5)

[2.         3.41421356 4.73205081]


In [43]:
#Broadcasting

In [44]:
array_6 = np.array([1,2,3,4,5,6,7,8,9])

In [45]:
array_6[0:5] = 100
print(array_6)

[100 100 100 100 100   6   7   8   9]


In [46]:
array_6[3:7] = 1

In [47]:
print(array_6)

[100 100 100   1   1   1   1   8   9]


In [48]:
#Matrices

In [49]:
M =np.array([[1,2,3],[7,8,9],[4,5,6]])

In [50]:
M

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [51]:
L = np.linspace(1,9,9)

In [52]:
L

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [53]:
M = L.reshape(3,3)

In [54]:
M

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [55]:
M3 = np.random.randn(1,7,4)
M3

array([[[ 1.54580003, -1.02408376,  0.12856356, -2.00937755],
        [ 0.34752267, -0.48360387, -1.48854116, -1.00957829],
        [-0.21482823,  0.07672649, -1.28337538, -0.20751038],
        [ 0.56546212,  1.17003931, -0.46227104,  0.45827406],
        [-1.1163786 , -0.97900288,  0.73158083,  0.20319954],
        [-1.135802  , -1.23410542,  0.26177482, -0.49281863],
        [-0.28174906, -0.11418519, -0.86554133,  1.43868284]]])

In [56]:
N = np.random.randn(1,4)
N

array([[-0.66452398,  0.39925649,  0.50101686, -0.17525263]])

In [57]:
# Identity matrix
I = np.eye(3,4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [58]:
# Zero Matrix 
Z = np.zeros([3,5])
Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [59]:
D = np.diag(M)

In [60]:
D

array([1., 5., 9.])

In [61]:
E = np.diag(D)

In [62]:
E

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

In [66]:
O = np.ones([3,4])
O

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [80]:
M1 = sy.Matrix([[1,2,3],[7,0,6],[7,1,9]])

In [81]:
M1

Matrix([
[1, 2, 3],
[7, 0, 6],
[7, 1, 9]])

In [96]:
V = M1.inv()
V

Matrix([
[  2/9,    5/9,  -4/9],
[  7/9,    4/9,  -5/9],
[-7/27, -13/27, 14/27]])

In [84]:
V.det()

-1/27

In [69]:
V.dot(M)

array([[ 12. ,  12. ,  12. ],
       [-10. , -16. , -14. ],
       [  1.5,   4. ,   6.5]])

In [85]:
M1.det()

-27

In [97]:
V.row_del(0)

In [98]:
V

Matrix([
[  7/9,    4/9,  -5/9],
[-7/27, -13/27, 14/27]])

In [101]:
P = sy.Matrix(np.random.randint(1,10,size=(4,3)))

In [102]:
P

Matrix([
[3, 9, 2],
[2, 4, 2],
[5, 8, 7],
[3, 3, 8]])

In [108]:
Q = sy.Matrix(np.random.randint(1,10,size=(3,4)))

In [109]:
Q

Matrix([
[2, 8, 3, 3],
[7, 6, 9, 1],
[1, 7, 1, 3]])

In [110]:
R = np.matmul(P,Q)

In [111]:
R

array([[71, 92, 92, 24],
       [34, 54, 44, 16],
       [73, 137, 94, 44],
       [35, 98, 44, 36]], dtype=object)

In [112]:
sy.Matrix(R)

Matrix([
[71,  92, 92, 24],
[34,  54, 44, 16],
[73, 137, 94, 44],
[35,  98, 44, 36]])